version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/lrills/helm-unittest
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - helm-unittest-deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - helm-unittest-deps-{{ .Branch }}-
            - helm-unittest-deps-
      - run:
          name: Download deps
          command: make deps
      - save_cache:
          key: helm-unittest-deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Test
          command: make test
      - run:
          name: Check
          command: make check GIT_VERSION="${CIRCLE_TAG}"

  distribute:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/lrills/helm-unittest
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - helm-unittest-deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - helm-unittest-deps-{{ .Branch }}-
            - helm-unittest-deps-
      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Build binaries
          command: make dist
      - run:
          name: Upload binaries
          command: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} $CIRCLE_TAG _dist/

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - distribute:
          requires:
            - test
          filters:
            tags:
              only: /v\d+\.\d+\.\d+(-[\w\.-]*)?(\+[\w\.-]*)?/
            branches:
              ignore: /.*/
