version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /app
    steps:
      - checkout
      # - run:
      #     name: Get dep
      #     command: |
      #       curl -o install-dep.sh https://raw.githubusercontent.com/golang/dep/master/install.sh
      #       chmod +x install-dep.sh
      #       ./install-dep.sh
      - restore_cache:
          keys:
            - helm-unittest-deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - helm-unittest-deps-{{ .Branch }}-
            - helm-unittest-deps-
      # - run:
      #     name: Check dep status
      #     command: dep status -v
      - run:
          name: Download deps
          command: make deps
      - save_cache:
          key: helm-unittest-deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Test
          command: make test
      - run:
          name: Check formated
          command: "! gofmt -l . 2>&1 | read"

  distribute:
    docker:
      - image: golang:1.12
    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          keys:
            - helm-unittest-deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - helm-unittest-deps-{{ .Branch }}-
            - helm-unittest-deps-
      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Build binaries
          command: make dist
      - run:
          name: Upload binaries
          command: ghr -u $CIRCLE_USERNAME $CIRCLE_TAG _dist

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - distribute:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)?/
            branches:
              ignore: /.*/
